config/routes.rb
Rails.application.routes.draw do
  resources :formations
  #devise_for :users
  devise_for :users, path: 'auth',
   path_names: {
   sign_in: 'login',
    sign_out: 'logout',
     password: 'secret',
      confirmation: 'verification',
       #unlock: 'unblock',
        registration: 'register',
         sign_up: 'cmon_let_me_in' }
  resources :cours
  get 'page/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "page#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cour.rb
class Cour < ApplicationRecord
  has_one_attached :thumbnail do |attachable|
    attachable.variant :thumb, resize_to_limit: [1000, 900]
    attachable.variant :thumbindex, resize_to_limit: [500, 400]
  end

  has_one_attached :video

  validates_presence_of :title, :thumbnail

  has_rich_text :content
end

app/models/formation.rb
class Formation < ApplicationRecord
    validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cours_controller.rb
class CoursController < ApplicationController
  before_action :set_cour, only: %i[show edit update destroy]

  # GET /cours or /cours.json
  def index
    @cours = Cour.all
  end

  # GET /cours/1 or /cours/1.json
  def show
    if !user_signed_in?
      redirect_to root_path, notice: "Vous devez vous connecté."
    end
  end

  # GET /cours/new
  def new
    @cour = Cour.new
  end

  # GET /cours/1/edit
  def edit
  end

  # POST /cours or /cours.json
  def create
    @cour = Cour.new(cour_params)
    respond_to do |format|
      if @cour.save
        format.html do
          redirect_to cour_url(@cour), notice: "Cour was successfully created."
        end
        format.json { render :show, status: :created, location: @cour }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cours/1 or /cours/1.json
  def update
    respond_to do |format|
      if @cour.update(cour_params)
        format.html do
          redirect_to cour_url(@cour), notice: "Cour was successfully updated."
        end
        format.json { render :show, status: :ok, location: @cour }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cours/1 or /cours/1.json
  def destroy
    @cour.destroy

    respond_to do |format|
      format.html do
        redirect_to cours_url, notice: "Cour was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cour
    @cour = Cour.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cour_params
    params.require(:cour).permit(:title, :content, :thumbnail, :video)
  end
end

app/controllers/formations_controller.rb
class FormationsController < ApplicationController
  before_action :set_formation, only: %i[ show edit update destroy ]

  # GET /formations or /formations.json
  def index
    @formations = Formation.all
  end

  # GET /formations/1 or /formations/1.json
  def show
  end

  # GET /formations/new
  def new
    @formation = Formation.new
  end

  # GET /formations/1/edit
  def edit
  end

  # POST /formations or /formations.json
  def create
    @formation = Formation.new(formation_params)

    respond_to do |format|
      if @formation.save
        format.html { redirect_to formation_url(@formation), notice: "Formation was successfully created." }
        format.json { render :show, status: :created, location: @formation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @formation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formations/1 or /formations/1.json
  def update
    respond_to do |format|
      if @formation.update(formation_params)
        format.html { redirect_to formation_url(@formation), notice: "Formation was successfully updated." }
        format.json { render :show, status: :ok, location: @formation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @formation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formations/1 or /formations/1.json
  def destroy
    @formation.destroy

    respond_to do |format|
      format.html { redirect_to formations_url, notice: "Formation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formation
      @formation = Formation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def formation_params
      params.require(:formation).permit(:title)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cours_helper.rb
module CoursHelper
end

app/helpers/formations_helper.rb
module FormationsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/cours/_cour.html.erb
<div id="<%= dom_id cour %>" style="margin-top: -64px">
  <% if cour.video.attached? %>
    <div class="d-flex justify-content-center">
      <%= video_tag(url_for(cour.video), controls: true, width: "1300px") %>
    </div>
  <% else %>
    <p>
      <%= image_tag url_for(cour.thumbnail.variant(:thumb)) %>
    </p>
  <% end %>
  <br>

  <p>
    <strong>Title:</strong>
    <%= cour.title %>
  </p>

  <p>
    <strong>Posted:</strong>
    <%= time_tag cour.created_at, "data-local": "time-ago" %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= cour.content %>
  </p>

</div>

app/views/cours/_form.html.erb
<%= form_with(model: cour) do |form| %>
  <% if cour.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cour.errors.count, "error") %> prohibited this cour from being saved:</h2>

      <ul>
        <% cour.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-md-4">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>
  <br>

  <div class="form-group col-md-4">
    <%= form.label :miniature, style: "display: block" %>
    <%= form.file_field :thumbnail, class:"form-control" %>
  </div>
  <br>

  <div class="form-group col-md-4">
    <%= form.label :video, style: "display: block" %>
    <%= form.file_field :video, class:"form-control" %>
  </div>
  <br>

  <div class="form-group">
    <%= form.label :content, style: "display: block;" %>
    <%= form.rich_text_area :content, class:"form-control" %>
  </div>
<br>
  <div class="form-group">
    <%= form.submit "Enregistrer", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/cours/edit.html.erb
<div class="container-xxl py-5">
  <div class="container">
    <h1>Editing cour</h1>

    <%= render "form", cour: @cour %>

    <br>

    <div>
      <%= link_to "Show this cour", @cour %> |
      <%= link_to "Back to cours", cours_path %>
      </div>
  </div>
</div>

app/views/cours/index.html.erb
<%# @cours.each do |cour| %>
    <%#= render cour %>
    <!--p>
        <%#= link_to "Show this cour", cour %>
    </p-->
<% #end %>
    <p style="color: green"><%#= notice %></p>
<% if user_signed_in? %>
    <h1><%= link_to "Ajouter un cours", new_cour_path %></h1>
<% end %>


    <!-- Header Start -->
    <div class="container-fluid bg-primary py-5 mb-5 page-header">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-10 text-center">
                    <h1 class="display-3 text-white animated slideInDown">Courses</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center">
                            <li class="breadcrumb-item"><a class="text-white" href="#">Home</a></li>
                            <li class="breadcrumb-item"><a class="text-white" href="#">Pages</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">Courses</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <div id="cours">
    </div>

    <!-- Courses Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Courses</h6>
                <h1 class="mb-5">Popular Courses</h1>
            </div>
            <div class="row g-4 justify-content-center">
            <% @cours.each do |cour| %>
                <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                    <div class="course-item bg-light">
                        <div class="position-relative overflow-hidden">
                            <!-- img class="img-fluid" src="img/course-1.jpg" alt="" -->
                            <%= image_tag url_for(cour.thumbnail), class:"img-fuild", alt:"", style:"" %>
                            <div class="w-100 d-flex justify-content-center position-absolute bottom-0 start-0 mb-4">
                                <%= link_to "Lire le cours", cour, class:"flex-shrink-0 btn btn-sm btn-primary px-3 border-end", style:"border-radius: 30px 0 0 30px;" %>
                                <a href="#" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 0 30px 30px 0;">Join Now</a>
                            </div>
                        </div>
                        <div class="text-center p-4 pb-0">
                            <h3 class="mb-0">$149.00</h3>
                            <div class="mb-3">
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small>(123)</small>
                            </div>
                            <h5 class="mb-4"><%= cour.title %></h5>
                        </div>
                        <div class="d-flex border-top">
                            <small class="flex-fill text-center border-end py-2"><i class="fa fa-user-tie text-primary me-2"></i>John Doe</small>
                            <small class="flex-fill text-center border-end py-2"><i class="fa fa-clock text-primary me-2"></i>1.49 Hrs</small>
                            <small class="flex-fill text-center py-2"><i class="fa fa-user text-primary me-2"></i>30 Students</small>
                        </div>
                    </div>
                </div>
            <% end %>

                <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
                    <div class="course-item bg-light">
                        <div class="position-relative overflow-hidden">
                            <%= image_tag "course-2.jpg", class:"img-fuild" %>
                            <div class="w-100 d-flex justify-content-center position-absolute bottom-0 start-0 mb-4">
                                <a href="#" class="flex-shrink-0 btn btn-sm btn-primary px-3 border-end" style="border-radius: 30px 0 0 30px;">Read More</a>
                                <a href="#" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 0 30px 30px 0;">Join Now</a>
                            </div>
                        </div>
                        <div class="text-center p-4 pb-0">
                            <h3 class="mb-0">$149.00</h3>
                            <div class="mb-3">
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small>(123)</small>
                            </div>
                            <h5 class="mb-4">Web Design & Development Course for Beginners</h5>
                        </div>
                        <div class="d-flex border-top">
                            <small class="flex-fill text-center border-end py-2"><i class="fa fa-user-tie text-primary me-2"></i>John Doe</small>
                            <small class="flex-fill text-center border-end py-2"><i class="fa fa-clock text-primary me-2"></i>1.49 Hrs</small>
                            <small class="flex-fill text-center py-2"><i class="fa fa-user text-primary me-2"></i>30 Students</small>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
                    <div class="course-item bg-light">
                        <div class="position-relative overflow-hidden">
                            <!-- img class="img-fluid" src="img/course-3.jpg" alt="" -->
                            <%= image_tag "course-3.jpg", class:"img-fuild", alt:"", style:"" %>
                            <div class="w-100 d-flex justify-content-center position-absolute bottom-0 start-0 mb-4">
                                <a href="#" class="flex-shrink-0 btn btn-sm btn-primary px-3 border-end" style="border-radius: 30px 0 0 30px;">Read More</a>
                                <a href="#" class="flex-shrink-0 btn btn-sm btn-primary px-3" style="border-radius: 0 30px 30px 0;">Join Now</a>
                            </div>
                        </div>
                        <div class="text-center p-4 pb-0">
                            <h3 class="mb-0">$149.00</h3>
                            <div class="mb-3">
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small>(123)</small>
                            </div>
                            <h5 class="mb-4">Web Design & Development Course for Beginners</h5>
                        </div>
                        <div class="d-flex border-top">
                            <small class="flex-fill text-center border-end py-2"><i class="fa fa-user-tie text-primary me-2"></i>John Doe</small>
                            <small class="flex-fill text-center border-end py-2"><i class="fa fa-clock text-primary me-2"></i>1.49 Hrs</small>
                            <small class="flex-fill text-center py-2"><i class="fa fa-user text-primary me-2"></i>30 Students</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Courses End -->


    
        

app/views/cours/new.html.erb
<div class="container-xxl py-5">
  <div class="container">
    <h1>New cour</h1>

    <%= render "form", cour: @cour %>

    <br>

    <div>
      <%= link_to "Back to cours", cours_path %>
    </div>
  </div>
</div>

app/views/cours/show.html.erb
<div class="container-xxl py-5">
  <div class="container">
    <p style="color: green"><%= notice %></p>

    <%= render @cour %>

    <div>
      <%= link_to "Edit this cour", edit_cour_path(@cour) %> |
      <%= link_to "Back to cours", cours_path %>

      <%= button_to "Destroy this cour", @cour, method: :delete %>
    </div>
  </div>
</div>

app/views/formations/_form.html.erb
<%= form_with(model: formation) do |form| %>
  <% if formation.errors.any? %>
    <div class="alert alert-danger" style="color: red">
      <h2><%= pluralize(formation.errors.count, "error") %> prohibited this formation from being saved:</h2>

      <ul>
        <% formation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-md-4">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>
  <br>

  <div class="form-group">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/formations/_formation.html.erb
<div id="<%= dom_id formation %>">
  <p>
    <strong>Title:</strong>
    <%= formation.title %>
  </p>

</div>

app/views/formations/edit.html.erb
<div class="container-xxl py-5">
  <div class="container">
    <h1>Editer formation</h1>

    <%= render "form", formation: @formation %>

    <br>

    <div>
      <%= link_to "Show this formation", @formation %> |
      <%= link_to "Back to formations", formations_path %>
    </div>
    </div>
</div>

app/views/formations/index.html.erb
<div class="container-xxl py-5">
  <div class="container">
    <p style="color: green"><%= notice %></p>

      <h1>Formations</h1>

      <div id="formations">
        <% @formations.each do |formation| %>
          <%= render formation %>
          <p>
            <%= link_to "Show this formation", formation %>
          </p>
        <% end %>
      </div>

      <%= link_to "New formation", new_formation_path %>
  </div>
</div>

app/views/formations/new.html.erb
<div class="container-xxl py-5">
  <div class="container">
    <h1>Nouvelle formation</h1>

    <%= render "form", formation: @formation %>

    <br>

    <div>
      <%= link_to "Back to formations", formations_path %>
    </div>
  </div>
</div>

app/views/formations/show.html.erb
<div class="container-xxl py-5">
  <div class="container">
    <p style="color: green"><%= notice %></p>

    <%= render @formation %>

    <div>
      <%= link_to "Edit this formation", edit_formation_path(@formation) %> |
      <%= link_to "Back to formations", formations_path %>

      <%= button_to "Destroy this formation", @formation, method: :delete %>
    </div>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Education</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta content="" name="keywords">
    <meta content="" name="description">

  

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- CHECK THESE BELOW LINES OUT!!!   -->

  <!-- Favicon -->
    <!-- link href="img/favicon.ico" rel="icon" -->

    <!-- Libraries Stylesheet  -->
    <!--link href="lib/animate/animate.min.css" rel="stylesheet" -->
    <!-- link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" -->

    
    <!-- CHECK THESE ABOVE LINES OUT!!!   -->
    
    <%= stylesheet_link_tag "application", "actiontext.css", "style", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/shared/header" %>
    <br>
    <br>
    <br>

    <% if notice  %>
      <div class="alert alert-success" role="alert">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if alert  %>
      <div class="alert alert-danger" role="alert">
        <p class="alert"><%= alert %></p>
      </div>
    <% end  %>
    
    <%= yield %>

    <%= render "layouts/shared/footer" %>

  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Quick Link</h4>
                    <a class="btn btn-link" href="">About Us</a>
                    <a class="btn btn-link" href="">Contact Us</a>
                    <a class="btn btn-link" href="">Privacy Policy</a>
                    <a class="btn btn-link" href="">Terms & Condition</a>
                    <a class="btn btn-link" href="">FAQs & Help</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Contact</h4>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Rue 123, Paris, France</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Gallery</h4>
                    <div class="row g-2 pt-2">
                        <div class="col-4">
                            <!-- img class="img-fluid bg-light p-1" src="img/course-1.jpg" alt="" -->
                            <%= image_tag "course-1.jpg", class:"img-fluid bg-light p-1", alt:"" %>
                        </div>
                        <div class="col-4">
                            <!-- img class="img-fluid bg-light p-1" src="img/course-2.jpg" alt="" -->
                            <%= image_tag "course-2.jpg", class:"img-fluid bg-light p-1", alt:"" %>
                        </div>
                        <div class="col-4">
                            <!-- img class="img-fluid bg-light p-1" src="img/course-3.jpg" alt="" -->
                            <%= image_tag "course-3.jpg", class:"img-fluid bg-light p-1", alt:"" %>
                        </div>
                        <div class="col-4">
                            <!-- img class="img-fluid bg-light p-1" src="img/course-2.jpg" alt="" -->
                            <%= image_tag "course-2.jpg", class:"img-fluid bg-light p-1", alt:"" %>
                        </div>
                        <div class="col-4">
                            <!-- img class="img-fluid bg-light p-1" src="img/course-3.jpg" alt="" -->
                            <%= image_tag "course-3.jpg", class:"img-fluid bg-light p-1", alt:"" %>
                        </div>
                        <div class="col-4">
                            <!-- img class="img-fluid bg-light p-1" src="img/course-1.jpg" alt="" -->
                            <%= image_tag "course-1.jpg", class:"img-fluid bg-light p-1", alt:"" %>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-3">Newsletter</h4>
                    <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                        <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; <a class="border-bottom" href="#">Formation</a>, All Right Reserved.

                        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                        Designed By <a class="border-bottom" href="#">Formation</a><br><br>
                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <div class="footer-menu">
                            <a href="">Home</a>
                            <a href="">Cookies</a>
                            <a href="">Help</a>
                            <a href="">FQAs</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->

app/views/layouts/shared/_header.html.erb
<!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
        <a href="<%= root_path %>" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>Awform</h2>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">
                <%= link_to "Home", root_path, class:"nav-item nav-link active" %>
                <%= link_to "A propos", "#", class:"nav-item nav-link" %>
                <%= link_to "Cours", cours_path(), class:"nav-item nav-link" %>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu fade-down m-0">
                        <%= link_to "Notre Equipe", "#", class:"dropdown-item" %>
                        <%= link_to "Testimonial", "#", class:"dropdown-item" %>
                        <%= link_to "404 Page", "#", class:"dropdown-item" %>
                    </div>
                    </div>
                    <%= link_to "Contact", "#", class:"nav-item nav-link" %>
            </div>
            <% if !user_signed_in? %>
                <a href="<%= new_user_session_path() %>" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Se Connecter<i class="fa fa-arrow-right ms-3"></i></a>
            <% else %>
                <%= link_to "Se Deconnecter", destroy_user_session_path, method: :delete, class:"btn btn-primary py-4 px-lg-5 d-none d-lg-block" %>
            <% end %>
        </div>
    </nav>
    <!-- Navbar End -->